### ISSUE TITLE
Coffeescript - constructor(@vars) ->

### ISSUE THREAD

**Issue by dylan-baskind** [latos/heroin-js#3]
So in newer Coffeescript versions (at 1.9.2 and up) the constructor, member-variable shortcut syntax like:

```coffee
class SomeClass
  constructor: (@theVar) ->
   # do some stuff
```

Gets converted in the JS to:

```javascript
SomeClass = (function() {
  function SomeClass(_at_theVar) {
    this.theVar = _at_theVar;
  }

  return SomeClass;
```

So heroin complains about can't find _at_theVar.

Probably outside of Heroin's responsibilities to deal with something like that, but might be worth noting for Coffeescript peeps, that you need to do the more plodding inject then assign as member vars

```coffee
class SomeClass
  constructor: (theVar) ->
     @theVar = theVar
```

**Comment by latos** [comment]
Looks like only a problem with 1.9.0, coffeescript reverted this in 1.9.1 so it's no longer an issue.  In any case, it would be easy to address by overriding your injector's .annotate function to strip the _at_ prefixes.

FYI  I implemented these convenience helpers in heroin:

```
  Injector.createCoffeeAnnotator = function(chainedAnnotator) {
    var PREFIX = '_at_';
    var PREFIX_LEN = PREFIX.length;
    return Injector.transformingAnnotator(function(name) {
        if (name.substr(0, PREFIX_LEN) == PREFIX) {
          return name.substr(PREFIX_LEN);
        }
        return name;
      }, chainedAnnotator);
  }

  Injector.transformingAnnotator = function(mapFunc, chainedAnnotator) {
    chainedAnnotator = chainedAnnotator || funcParams;

    return function(fn) {
      var names = chainedAnnotator(fn)
      var l = names.length;
      for (var i = 0; i < l; i++) {
        names[i] = mapFunc(names[i]);
      }
      return names;
    };
  };
```

And the use in coffee would be:

```
di.annotate = Injector.createCoffeeAnnotator(di.annotate)
```

But I'm not going to submit this, since it was only a transient feature.  Code recorded here for posterity in case a similar issue comes up / example use of setting the annotate function.

**Comment by latos** [comment]
Added a test in c0257ba25e66f649998b247915d3ba63b3d0ea31
